version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  ac:
    lang: node-koa
    handler: ./ac
    image: ac:latest
    environment:
      write_timeout: 10s
      read_timeout: 10s
      mongo: openfaas-animal-mongod
